kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30080
    hostPort: 30080
- role: worker
  extraMounts:
  - hostPath: /tmp/lesson-mysql-pv
    containerPath: /data/lesson-mysql-pv
- role: worker
  extraMounts:
  - hostPath: /tmp/lesson-wordpress-pv
    containerPath: /data/lesson-wordpress-pv
