---
# Переменные для группы dev
environment: development
ansible_user: vagrant
ansible_ssh_private_key_file: "/home/user/lesson12/.vagrant/machines/dev/virtualbox/private_key"
ansible_python_interpreter: /usr/bin/python3
