---
# Переменные для группы prod
environment: production
ansible_user: vagrant
ansible_ssh_private_key_file: "/home/user/lesson12/.vagrant/machines/prod/virtualbox/private_key"
ansible_python_interpreter: /usr/bin/python3
