apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lesson.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "lesson.labels" . | nindent 4 }}
data:
  DB_HOST: {{ include "lesson.fullname" . }}-mysql
  DB_NAME: wordpress
  DB_USER: wpuser
  DB_PASSWORD: wppass123
