apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lesson.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "lesson.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "lesson.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "lesson.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "wordpress:latest"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: WORDPRESS_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: {{ include "lesson.fullname" . }}-config
              key: DB_HOST
        - name: WORDPRESS_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: {{ include "lesson.fullname" . }}-config
              key: DB_NAME
        - name: WORDPRESS_DB_USER
          valueFrom:
            configMapKeyRef:
              name: {{ include "lesson.fullname" . }}-config
              key: DB_USER
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "lesson.fullname" . }}-mysql-secrets
              key: mysql-password
        volumeMounts:
        - name: wordpress-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-storage
        persistentVolumeClaim:
          claimName: {{ include "lesson.fullname" . }}-pvc
