version: '3.8'
services:
  ui:
    image: ghcr.io/codeby-devops/ui:bug
    container_name: ui
    ports:
      - "9292:9292"
    environment:
      - POST_SERVICE_HOST=post
      - POST_SERVICE_PORT=5000
      - COMMENT_SERVICE_HOST=comment
      - COMMENT_SERVICE_PORT=9292
      - ZIPKIN_ENABLED=true
      - ZIPKIN_URL=http://zipkin:9411
    depends_on:
      - comment
      - post
      - zipkin

  post:
    image: ghcr.io/codeby-devops/post:bug
    container_name: post
    environment:
      - POST_DATABASE_HOST=post_db
      - POST_DATABASE=posts
      - ZIPKIN_ENABLED=true
      - ZIPKIN_URL=http://zipkin:9411
    depends_on:
      - post_db
      - zipkin
    ports:
      - "5000:5000"

  comment:
    image: ghcr.io/codeby-devops/comment:bug
    container_name: comment
    environment:
      - COMMENT_DATABASE_HOST=comment_db
      - COMMENT_DATABASE=comments
      - ZIPKIN_ENABLED=true
      - ZIPKIN_URL=http://zipkin:9411
    depends_on:
      - comment_db
      - zipkin
    ports:
      - "9293:9292"

  post_db:
    image: mongo:4.4
    container_name: post_db
    volumes:
      - post_db_data:/data/db

  comment_db:
    image: mongo:4.4
    container_name: comment_db
    volumes:
      - comment_db_data:/data/db

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"

volumes:
  post_db_data:
  comment_db_data:
